name: iac deployment
on: 
  workflow_dispatch:
    inputs:
      region:
        description: "Region"
        required: true
        default: "ap-northeast-1"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure aws credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}
      - name: Fetch terraform modules
        run: terraform init
      - name: Apply terraform
        run: terraform apply -auto-approve
